### ISSUE TITLE
Problems with Firefox Quantum with Netlify hosted site

### ISSUE THREAD

**Issue by carlca** [mozilla/firefox57-sprint#113]
```
macOS 10.13.1 High Sierra 
Firefox Quantum 57
```
If this is not the correct place for this issue report, please forgive me, and redirect me to the right place, thanks!

Hello, I have a website that is hosted at Netlify. The URL is https://relaxed-williams-d8a311.netlify.com/ I have the domain https://carlca.com which is configured to point to the same site. The problem is that while the site displays perfectly from the https://relaxed-williams-d8a311.netlify.com/ URL, some of the characters do not display properly with the https://carlca.com URL and they are pointing to the same site, Look at the social media symbols as examples of this difference in the display.

Both URLs display correctly in Chrome...

**Comment by MichaelKohler** [comment]
This indeed is the wrong place. This would be better suited to be posted in a web developer help forum like stackoverflow as this is not an issue with Firefox itself, but with the website.

In any case, I have taken a quick look at the problem:
1) With the latest Chrome version, https://carlca.com/ doesn't load the icons either
2) This is due to the fact that the font can't be loaded due to an issue with CORS:

```
 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://relaxed-williams-d8a311.netlify.com/fonts/fontawesome-webfont.woff2?v=4.6.3. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

You can read more about CORS here: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
