### ISSUE TITLE
Get 5 Reps and 5 Mozillians to review the content for clarity

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/firefox57-sprint#34]
We want to make sure the content is clear to everyone once we launch. I'd suggest to get 5 Reps as well as 5 Mozillians to review the content and sign off.

**Comment by couci** [comment]
FYI @kelimuttu is already reviewing this on a volunteer capability, as our A tester

**Comment by kelimuttu** [comment]
Hey all, I take a look on the doc this morning and here are some of my concerns: 

- Is there any feature that let us know which website has been tested? Cause if we don't have that, we might waste other people' time by asking them to test the same website.
- And apparently, Alexa only provide a limited number of 50 websites for the free account. In order to see the full list, we need to subscribe. So, I think we better come up with another options for the website reference. I can't think of anything right now tho'.

**Comment by MichaelKohler** [comment]
> Is there any feature that let us know which website has been tested? Cause if we don't have that, we might waste other people' time by asking them to test the same website.

The reporting form submits to a Google Form, so we have the links there. This could be exposed in a friendlier manner. However, I think the question is, do we only want X number of people to test a website?

> And apparently, Alexa only provide a limited number of 50 websites for the free account.

Oh, that's not nice. Even if we sign up, that would mean we need to curate the list ourselves. I'll think about this, maybe I'll have an idea.

**Comment by kelimuttu** [comment]
And we can probably put something in the website to encourage the host to ask the participants test their own favorite websites. Just so people is not only focus on the Alexa list.

**Comment by MichaelKohler** [comment]
@kelimuttu can you create separate issues for this so we can use this one to track the work of getting outside feedback?

**Comment by kelimuttu** [comment]
Do we still need it? I guess @couci will get the list and put it elsewhere.

**Comment by MichaelKohler** [comment]
Filed issue #48 for that. We have announced the website to the Reps and got some feedback. Some Reps have already forwarded/discussed with local communities, so I think this is fine for now.
