### ISSUE TITLE
Change Nightly to Beta

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/firefox57-sprint#50]
As by the time we run this Firefox 57 will be in Beta, we should change all mentions from Nightly to Beta including the links pointing to the download page.

**Comment by MichaelKohler** [comment]
@couci this will need your final decision

**Comment by couci** [comment]
I think we need to stick with nightly, I understand the problem you're posing but right now the comms and the video is about nightly and we also want to increase the downloads of the program

**Comment by julian-alarcon** [comment]
Same issue, don't get it. The repo information says:
"This is the repo for the Firefox 57 sprint https://firefoxsprint.mozilla.community/"
Also multiple Events have Firefox 57 as the target of the Spring and they will be using the Firefox Nightly version that will be 58.

**Comment by couci** [comment]
Hello,
yes you're right, nightly is now on 58 and beta is on 57 and our focus is 57. The reason we decided to go initially to Nightly was because we knew that the issues are going to be eventually uplifted. However, by asking the engineers we were told that nightly will be more unsustainable on 58 thus move to beta for better user experience.

@MichaelKohler for that reason I am reopening this one. Do you need to track the places we need change?

**Comment by MichaelKohler** [comment]
> @MichaelKohler for that reason I am reopening this one. Do you need to track the places we need change?

As far as I know, this is only on the "Host" page for now.

**Comment by julian-alarcon** [comment]
This page is still suggesting Nightly: https://firefoxsprint.mozilla.community/participant/

> You prefer to participate at the campaign from the comfort of your couch? That’s totally fine! Here is how:
> 
>     Install Nightly for Desktop

**Comment by julian-alarcon** [comment]
Also this is still suggesting to download Nightly:
https://firefoxsprint.mozilla.community/host/

**Comment by MichaelKohler** [comment]
This is done in the "newdesign" branch. I've also changed to the new video with the corrected phrase. This will be live once that branch is merged.
