### ISSUE TITLE
Hitting Geocode API limit

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/firefox57-sprint#60]
As we are currently using the Geocode API, we only have 2500 calls/day and 50 calls/second for free. As we do that for every event on our list, this will be a quite growing number.

This means, that once we reach a limit, we won't get any more results and therefore can't show the event on the map.

There are 2 possibilities:
1) Pay for a premium plan (https://developers.google.com/maps/documentation/geocoding/usage-limits)
2) Create a microservice that caches the lookup data and exposes an API endpoint for the Firefox Quantum sprint website

@couci @lkappeler what do you think?

**Comment by lkappeler** [comment]
Another simple solution could be to store the coordinates manually in spreadsheet, since this is our data source.
An the using the GEO Data API only as fallback if no coordinates are given.

The coordinates could ether be added in the registration form. The simple version would be to add two fields (lat, lng), the advanced version a location picker (relates to #39).
Another option could be to manually insert the in to the spreadsheet.  [Pick coordinates online](https://www.gps-coordinates.net/)

I would tend to **not** implement the caching micro-service Michael suggested, since besides implementing the service, there would be some additional task like hosting dns etc. for the service itself. In generell it is a good Idea but more likely a workaround than a solution. (We basically only would avoid the payment fees and have a "not as good" caching maybe also response time than the native google API ). Instead of I would build a Event rest API point to enrich the spreadsheet data with coordinates resolved form the Geodata API.

**Comment by MichaelKohler** [comment]
Thanks for the feedback!

> I would tend to not implement the caching micro-service Michael suggested, since besides implementing the service, there would be some additional task like hosting dns etc. for the service itself. In generell it is a good Idea but more likely a workaround than a solution. 

True.

> Another simple solution could be to store the coordinates manually in spreadsheet

We want to avoid any manual interactions needed, as we have enough to do anyway ;)

> Instead of I would build a Event rest API point to enrich the spreadsheet data with coordinates resolved form the Geodata API.

.. or just a service that runs somewhere and populates the lat/lng into the spreadsheet (as we discussed already). I think that would be the best way as that could be hosted anywhere and would never directly be called from the website.

**Comment by MichaelKohler** [comment]
BTW, 1) is not an option, as this would require a lot of money that can be saved through caching/requesting it once.

**Comment by MichaelKohler** [comment]
@lkapper is working on this here: https://github.com/lkappeler/geodata-fetcher

**Comment by lkappeler** [comment]
@MichaelKohler Still have this in my todos will have a look at it tonight or tomorrow. I'll give you an update after I tackled this.
